<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Room;
use Carbon\Carbon;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rooms = [
            // Floor 1
            [
                'room_number' => '101',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Standard',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 12500,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '102',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Standard',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 12500,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '103',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Standard',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 12500,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '104',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Standard',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 12500,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '105',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Standard',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 12500,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '106',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Standard',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 12500,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '107',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 4,
                'view' => 'Standard',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            [
                'room_number' => '108',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 4,
                'view' => 'Standard',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 1,
                'status_id' => 1,
            ],
            // Floor 2
            [
                'room_number' => '207',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '208',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '209',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '210',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '211',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '212',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => true,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '213',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 4,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 20000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '214',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 4,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 20000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '215',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '216',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => true,
                'comments' => '',
                'price_cents' => 15000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '217',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 4,
                'view' => 'Mountain',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 20000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '218',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Lake',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 17500,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '219',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Lake',
                'babybed' => true,
                'for_disabled' => true,
                'comments' => '',
                'price_cents' => 17500,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '220',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Lake',
                'babybed' => true,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 30000,
                'room_type_id' => 3,
                'status_id' => 1,
            ],
            // 3rd Floor
            [
                'room_number' => '301',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Lake',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 20000,
                'room_type_id' => 2,
                'status_id' => 1,
            ],
            [
                'room_number' => '302',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Lake',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 27500,
                'room_type_id' => 3,
                'status_id' => 1,
            ],
            [
                'room_number' => '303',
                'status_since' => Carbon::now(),
                'status_notes' => 'Room has been set up.',
                'capacity' => 2,
                'view' => 'Lake',
                'babybed' => false,
                'for_disabled' => false,
                'comments' => '',
                'price_cents' => 27500,
                'room_type_id' => 3,
                'status_id' => 1,
            ],
        ];

        foreach ($rooms as $roomData) {
            Room::create($roomData);
        }
    }
}