USE MASTER;

-- Create database named music
CREATE DATABASE music;
GO

-- Use the database music
USE music;

-- Create table named album
CREATE TABLE album(
	albumID		INT			IDENTITY(1,1)	,
	position	INT			NOT NULL		,
	year		INT							,
	name		VARCHAR(70) NOT NULL		,
	artist		VARCHAR(60) NOT NULL		,
	genre		VARCHAR(20) NOT NULL		,
	subgenre	VARCHAR(20)
);

-- Add primary key (albumID) to table album
ALTER TABLE album
ADD CONSTRAINT PK_albumID
PRIMARY KEY (albumID);

-- Insert 500 records in table album
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (1,1967,'Sgt. Pepper''s Lonely Hearts Club Band','The Beatles','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (2,1966,'Pet Sounds','The Beach Boys','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (3,1966,'Revolver','The Beatles','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (4,1965,'Highway 61 Revisited','Bob Dylan','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (5,1965,'Rubber Soul','The Beatles','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (6,1971,'Whats Going On','Marvin Gaye','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (7,1972,'Exile on Main St.','The Rolling Stones','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (8,1979,'London Calling','The Clash','Rock','Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (9,1966,'Blonde on Blonde','Bob Dylan','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (10,1968,'The Beatles (The White name)','The Beatles','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (11,1976,'The Sun Sessions','Elvis Presley','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (12,1959,'Kind of Blue','Miles Davis','Jazz','Modal');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (13,1967,'The Velvet Underground & Nico','The Velvet Underground','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (14,1969,'Abbey Road','The Beatles','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (15,1967,'Are You Experienced','The Jimi Hendrix Experience','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (16,1975,'Blood on the Tracks','Bob Dylan','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (17,1991,'Nevermind','Nirvana','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (18,1975,'Born to Run','Bruce Springsteen','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (19,1968,'Astral Weeks','Van Morrison','Jazz', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (20,1982,'Thriller','Michael Jackson','Funk / Soul','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (21,1982,'The Great Twenty_Eight','Chuck Berry','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (22,1990,'The Complete Recordings','Robert Johnson','Blues','Delta Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (23,1970,'John Lennon/Plastic Ono Band','John Lennon / Plastic Ono Band','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (24,1973,'Innervisions','Stevie Wonder','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (25,1963,'Live at the Apollo 1962','James Brown','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (26,1977,'Rumours','Fleetwood Mac','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (27,1987,'The Joshua Tree','U2','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (28,1971,'Who''s Next','The Who','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (29,1969,'Led Zeppelin','Led Zeppelin','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (30,1971,'Blue','Joni Mitchell','Pop','Acoustic');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (31,1965,'Bringing It All Back Home','Bob Dylan','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (32,1969,'Let It Bleed','The Rolling Stones','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (33,1976,'Ramones','Ramones','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (34,1968,'Music From Big Pink','The Band','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (35,1972,'The Rise and Fall of Ziggy Stardust and the Spiders From Mars','David Bowie','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (36,1971,'Tapestry','Carole King','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (37,1976,'Hotel California','Eagles','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (38,2001,'The Anthology','Muddy Waters','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (39,1963,'Please Please Me','The Beatles','Rock','Beat');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (40,1967,'Forever Changes','Love','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (41,1977,'Never Mind the Bollocks Here''s the Sex Pistols','Sex Pistols','Rock','Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (42,1967,'The Doors','The Doors','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (43,1973,'The Dark Side of the Moon','Pink Floyd','Rock','Prog Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (44,1975,'Horses','Patti Smith','Rock','Art Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (45,1969,'The Band (The Brown name)','The Band','Classical','Stage & Screen');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (46,1984,'Legend: The Best of Bob Marley and The Wailers','Bob Marley & The Wailers','Reggae','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (47,1965,'A Love Supreme','John Coltrane','Jazz','Free Jazz');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (48,1988,'It Takes a Nation of Millions to Hold Us Back','Public Enemy','Hip Hop','Conscious');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (49,1971,'At Fillmore East','The Allman Brothers Band','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (50,1957,'Here''s Little Richard','Little Richard','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (51,1970,'Bridge Over Troubled Water','Simon & Garfunkel','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (52,1975,'Greatest Hits','Al Green','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (53,1964,'Meet The Beatles!','The Beatles','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (54,1991,'The Birth of Soul','Ray Charles','Jazz','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (55,1968,'Electric Ladyland','The Jimi Hendrix Experience','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (56,1956,'Elvis Presley','Elvis Presley','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (57,1976,'Songs in the Key of Life','Stevie Wonder','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (58,1968,'Beggars Banquet','The Rolling Stones','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (59,1976,'Chronicle: The 20 Greatest Hits','Creedence Clearwater Revival','Rock','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (60,1969,'Trout Mask Replica','Captain Beefheart & His Magic Band','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (61,1970,'Greatest Hits','Sly & The Family Stone','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (62,1987,'Appetite for Destruction','Guns N'' Roses','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (63,1991,'Achtung Baby','U2','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (64,1971,'Sticky Fingers','The Rolling Stones','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (65,1991,'Back to Mono (1958-1969)','Phil Spector','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (66,1970,'Moondance','Van Morrison','Jazz','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (67,2000,'Kid A','Radiohead','Electronic', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (68,1979,'Off the Wall','Michael Jackson','Funk / Soul','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (69,1971,'[Led Zeppelin IV]','Led Zeppelin','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (70,1977,'The Stranger','Billy Joel','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (71,1986,'Graceland','Paul Simon','Jazz','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (72,1972,'Superfly','Curtis Mayfield','Funk / Soul','Stage & Screen');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (73,1975,'Physical Graffiti','Led Zeppelin','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (74,1970,'After the Gold Rush','Neil Young','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (75,1991,'Star Time','James Brown','Funk / Soul', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (76,1984,'Purple Rain','Prince and the Revolution','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (77,1980,'Back in Black','AC/DC','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (78,1965,'Otis Blue: Otis Redding Sings Soul','Otis Redding','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (79,1969,'Led Zeppelin II','Led Zeppelin','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (80,1971,'Imagine','John Lennon','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (81,1977,'The Clash','The Clash','Rock','Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (82,1972,'Harvest','Neil Young','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (83,1967,'Axis: Bold as Love','The Jimi Hendrix Experience','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (84,1967,'I Never Loved a Man the Way I Love You','Aretha Franklin','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (85,1968,'Lady Soul','Aretha Franklin','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (86,1984,'Born in the U.S.A.','Bruce Springsteen','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (87,1979,'The Wall','Pink Floyd','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (88,1968,'At Folsom Prison','Johnny Cash','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (89,1969,'Dusty in Memphis','Dusty Springfield','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (90,1972,'Talking Book','Stevie Wonder','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (91,1973,'Goodbye Yellow Brick Road','Elton John','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (92,1978,'20 Golden Greats','Buddy Holly','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (93,1987,'Sign Peace the Times','Prince','Rock','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (94,1984,'40 Greatest Hits','Hank Williams','Folk', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (95,1970,'Bitches Brew','Miles Davis','Jazz', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (96,1969,'Tommy','The Who','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (97,1963,'The Freewheelin'' Bob Dylan','Bob Dylan','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (98,1978,'This year''s Model','Elvis Costello','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (99,1971,'There''s a Riot Goin'' On','Sly & The Family Stone','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (100,1968,'Odessey and Oracle','The Zombies','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (101,1955,'In the Wee Small Hours','Frank Sinatra','Jazz', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (102,1966,'Fresh Cream','Cream','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (103,1959,'Giant Steps','John Coltrane','Jazz','Hard Bop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (104,1970,'Sweet Baby James','James Taylor','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (105,1962,'Modern Sounds in Country and Western Music','Ray Charles','Funk / Soul', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (106,1977,'Rocket to Russia','Ramones','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (107,2003,'Portrait of a Legend 1951-1964','Sam Cooke','Latin','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (108,1971,'Hunky Dory','David Bowie','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (109,1966,'Aftermath','The Rolling Stones','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (110,1970,'Loaded','The Velvet Underground','Rock','Art Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (111,1995,'The Bends','Radiohead','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (112,1966,'If You Can Believe Your Eyes and Ears','The Mamas and the Papas','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (113,1974,'Court and Spark','Joni Mitchell','Rock','Soft Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (114,1967,'Disraeli Gears','Cream','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (115,1967,'The Who Sell Out','The Who','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (116,1965,'Out of Our Heads','The Rolling Stones','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (117,1970,'Layla and Other Assorted Love Songs','Derek and the Dominos','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (118,2005,'Late Registration','Kanye West','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (119,1960,'At Last!','Etta James','Funk / Soul','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (120,1968,'Sweetheart of the Rodeo','The Byrds','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (121,1969,'Stand!','Sly & The Family Stone','Funk / Soul', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (122,1972,'The Harder They Come','Various artists','Reggae','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (123,1986,'Raising Hell','Run D.M.C.','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (124,1967,'Moby Grape','Moby Grape','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (125,1971,'Pearl','Janis Joplin','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (126,1973,'Catch a Fire','The Wailers','Reggae','Roots Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (127,1967,'Younger Than Yesterday','The Byrds','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (128,1973,'Raw Power','Iggy and The Stooges','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (129,1980,'Remain in Light','Talking Heads','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (130,1977,'Marquee Moon','Television','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (131,1970,'Paranoid','Black Sabbath','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (132,1977,'Saturday Night Fever: The Original Movie Sound Track','Various artists','Electronic','Stage & Screen');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (133,1973,'The Wild, the Innocent & the E Street Shuffle','Bruce Springsteen','Rock', 'Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (134,1994,'Ready to Die','The Notorious B.I.G.','Hip Hop', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (135,1992,'Slanted and Enchanted','Pavement','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (136,1974,'Greatest Hits','Elton John','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (137,1985,'Tim','The Replacements','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (138,1992,'The Chronic','Dr. Dre','Hip Hop','Gangsta');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (139,1974,'Rejuvenation','The Meters','Funk / Soul','Bayou Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (140,1978,'Parallel Lines','Blondie','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (141,1965,'Live at the Regal','B.B. King','Blues','Chicago Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (142,1963,'A Christmas Gift for You From Phil Spector','Phil Spector','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (143,1968,'Gris-Gris, Dr. John','the Night Tripper','Jazz', 'Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (144,1988,'Straight Outta Compton','N.W.A','Hip Hop', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (145,1977,'Aja','Steely Dan','Jazz','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (146,1967,'Surrealistic Pillow','Jefferson Airplane','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (147,1970,'Deja vu','Crosby, Stills, Nash & Young', 'Rock', 'Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (148,1973,'Houses of the Holy','Led Zeppelin','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (149,1969,'Santana','Santana','Rock','Latin');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (150,1978,'Darkness on the Edge of Town','Bruce Springsteen','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (151,2004,'Funeral','Arcade Fire','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (152,1979,'The B 52''s / Play Loud','The B 52''s','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (153,1991,'The Low End Theory','A Tribe Called Quest','Hip Hop','Conscious');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (154,1958,'Moanin'' in the Moonlight','Howlin'' Wolf','Blues','Chicago Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (155,1980,'Pretenders','Pretenders','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (156,1989,'Paul''s Boutique','Beastie Boys','Hip Hop','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (157,1980,'Closer','Joy Division','Rock','Post-Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (158,1975,'Captain Fantastic and the Brown Dirt Cowboy','Elton John','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (159,1975,'Alive!','KISS','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (160,1971,'Electric Warrior','T. Rex','Rock','Glam');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (161,1968,'The Dock of the Bay','Otis Redding','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (162,1997,'OK Computer','Radiohead','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (163,1982,'1999','Prince','Funk / Soul','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (164,2002,'The Very Best of Linda Ronstadt','Linda Ronstadt','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (165,1973,'Lets Get It On','Marvin Gaye','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (166,1982,'Imperial Bedroom','Elvis Costello & The Attractions','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (167,0,'Master of Puppets','Metallica','XX','XX');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (168,1977,'My Aim Is True','Elvis Costello','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (169,1977,'Exodus','Bob Marley & The Wailers','Reggae', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (170,1970,'Live at Leeds','The Who','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (171,1968,'The Notorious Byrd Brothers','The Byrds','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (172,1971,'Every Picture Tells a Story','Rod Stewart','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (173,1972,'Something/Anything?','Todd Rundgren','Rock','Power Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (174,1976,'Desire','Bob Dylan','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (175,1970,'Close to You','Carpenters','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (176,1976,'Rocks','Aerosmith','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (177,1978,'One Nation Under a Groove','Funkadelic','Funk / Soul','P.Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (178,1992,'The Anthology: 1961-1977','Curtis Mayfield and The Impressions','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (179,2001,'The Definitive Collection','ABBA','Electronic','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (180,1965,'The Rolling Stones, Now!','The Rolling Stones','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (181,1974,'Natty Dread','Bob Marley & The Wailers','Reggae','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (182,1975,'Fleetwood Mac','Fleetwood Mac','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (183,1975,'Red Headed Stranger','Willie Nelson','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (184,1990,'The Immaculate Collection','Madonna','Electronic','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (185,1969,'The Stooges','The Stooges','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (186,1973,'Fresh','Sly & The Family Stone','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (187,1986,'So','Peter Gabriel','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (188,1967,'Buffalo Springfield Again','Buffalo Springfield','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (189,1969,'Happy Trails','Quicksilver Messenger Service','Rock','Acid Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (190,1969,'From Elvis in Memphis','Elvis Presley','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (191,1970,'Fun House','The Stooges','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (192,1969,'The Gilded Palace of Sin','The Flying Burrito Brothers','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (193,1994,'Dookie','Green Day','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (194,1972,'Transformer','Lou Reed','Rock','Glam');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (195,1966,'Blues Breakers With Eric Clapton (The Beano name)','John Mayall & The Bluesbreakers','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (196,1998,'Nuggets: Original Artyfacts From the First Psychedelic Era,1965-1968','Various artists','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (197,1983,'Murmur','R.E.M.','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (198,1967,'The Best of Little Walter','Little Walter','Blues', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (199,2001,'Is This It','The Strokes','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (200,1979,'Highway to Hell','AC/DC','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (201,1994,'The Downward Spiral','Nine Inch Nails','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (202,1966,'Parsley, Sage, Rosemary and Thyme','Simon & Garfunkel', 'Rock', 'Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (203,1987,'Bad','Michael Jackson','Funk / Soul','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (204,2006,'Modern Times','Bob Dylan','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (205,1968,'Wheels of Fire','Cream','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (206,1980,'Dirty Mind','Prince','Funk / Soul','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (207,1970,'Abraxas','Santana','Rock','Latin');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (208,1970,'Tea for the Tillerman','Cat Stevens','Rock','Stage & Screen');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (209,1991,'Ten','Pearl Jam','Rock','Grunge');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (210,1969,'Everybody Knows This Is Nowhere','Neil Young & Crazy Horse','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (211,1975,'Wish You Were Here','Pink Floyd','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (212,1994,'Crooked Rain Crooked Rain','Pavement','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (213,1981,'Tattoo You','The Rolling Stones','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (214,1991,'Proud Mary: The Best of Ike and Tina Turner','Ike & Tina Turner','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (215,1973,'New York Dolls','New York Dolls','Rock','Glam');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (216,1986,'Bo Diddley / Go Bo Diddley','Bo Diddley','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (217,1961,'Two Steps From the Blues','Bobby Blue Bland','Funk / Soul','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (218,1986,'The Queen Is Dead','The Smiths','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (219,1986,'Licensed to Ill','Beastie Boys','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (220,1970,'Look-Ka Py Py','The Meters','Funk / Soul','Bayou Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (221,1991,'Loveless','My Bloody Valentine','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (222,1972,'New Orleans Piano','Professor Longhair','Funk / Soul','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (223,1983,'War','U2','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (224,1999,'The Neil Diamond Collection','Neil Diamond','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (225,2004,'American Idiot','Green Day','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (226,1982,'Nebraska','Bruce Springsteen','Rock','Acoustic');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (227,1989,'Doolittle','Pixies','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (228,1987,'Paid in Full','Eric B. & Rakim','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (229,1975,'Toys in the Attic','Aerosmith','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (230,1989,'Nick of Time','Bonnie Raitt','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (231,1975,'A Night at the Opera','Queen','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (232,1972,'The Kink Kronikles','The Kinks','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (233,1965,'Mr. Tambourine Man','The Byrds','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (234,1968,'Bookends','Simon & Garfunkel','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (235,2000,'The Ultimate Collection','Patsy Cline','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (236,1992,'Mr. Excitement!','Jackie Wilson','Funk / Soul','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (237,1965,'My Generation','The Who','Rock','Mod');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (238,1962,'Howlin'' Wolf','Howlin'' Wolf','Blues','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (239,1989,'Like a Prayer','Madonna','Electronic','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (240,1972,'Can''t Buy a Thrill','Steely Dan','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (241,1984,'Let It Be','The Replacements','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (242,1984,'Run D.M.C.','Run D.M.C.','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (243,1970,'Black Sabbath','Black Sabbath','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (244,2000,'The Marshall Mathers LP','Eminem','Hip Hop','Pop Rap');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (245,1993,'All Killer No Filler! The Jerry Lee Lewis Anthology','Jerry Lee Lewis','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (246,1966,'Freak Out!','The Mothers of Invention','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (247,1969,'Live/Dead','The Grateful Dead','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (248,1959,'The Shape of Jazz to Come','Ornette Coleman','Jazz','Free Jazz');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (249,1992,'Automatic for the People','R.E.M.','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (250,1996,'Reasonable Doubt','Jay Z','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (251,1977,'Low','David Bowie','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (252,2001,'The Blueprint','Jay Z','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (253,1980,'The River','Bruce Springsteen','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (254,1966,'Complete & Unbelievable: The Otis Redding Dictionary of Soul','Otis Redding','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (255,1991,'Metallica (The Black name)','Metallica','Rock','Heavy Metal');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (256,1977,'Trans Europa Express','Kraftwerk','Electronic','Electro');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (257,1985,'Whitney Houston','Whitney Houston','Funk / Soul','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (258,1968,'The Kinks Are The Village Green Preservation Society','The Kinks','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (259,1997,'The Velvet Rope','Janet','Electronic','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (260,1978,'Stardust','Willie Nelson','Pop','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (261,1970,'American Beauty','Grateful Dead','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (262,1969,'Crosby, Stills & Nash','Crosby, Stills & Nash', 'Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (263,1988,'Tracy Chapman','Tracy Chapman','Rock','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (264,1970,'Workingman''s Dead','Grateful Dead','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (265,1959,'The Genius of Ray Charles','Ray Charles','Jazz','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (266,1968,'Child Is Father to the Man','Blood, Sweat & Tears','Rock', 'Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (267,1973,'Quadrophenia','The Who','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (268,1972,'Paul Simon','Paul Simon','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (269,1985,'Psychocandy','The Jesus and Mary Chain','Rock','Noise');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (270,1978,'Some Girls','The Rolling Stones','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (271,1965,'The Beach Boys Today!','The Beach Boys','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (272,1997,'Dig Me Out','Sleater Kinney','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (273,1966,'Going to a Go-Go','Smokey Robinson & The Miracles','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (274,1974,'Nightbirds','LaBelle','Funk / Soul','Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (275,1999,'The Slim Shady LP','Eminem','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (276,1975,'Mothership Connection','Parliament','Funk / Soul','P.Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (277,1989,'Rhythm Nation 1814','Janet Jackson','Electronic','Hip Hop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (278,1997,'Anthology of American Folk Music','Various','Blues','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (279,1973,'Aladdin Sane','David Bowie','Rock','Glam');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (280,2000,'All That You Can''t Leave Behind','U2','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (281,1994,'My Life','Mary J. Blige','Hip Hop','RnB/Swing');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (282,1964,'Folk Singer','Muddy Waters','Blues','Delta Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (283,1974,'Can''t Get Enough','Barry White','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (284,1978,'The Cars','The Cars','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (285,1972,'Music of My Mind','Stevie Wonder','Funk / Soul','Soul-Jazz');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (286,1972,'I''m Still in Love With You','Al Green','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (287,1980,'Los Angeles','X','Rock','Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (288,1968,'Anthem of the Sun','Grateful Dead','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (289,1967,'Something Else by The Kinks','The Kinks','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (290,1973,'Call Me','Al Green','Funk / Soul','Rhythm & Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (291,1977,'Talking Heads: 77','Talking Heads','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (292,1975,'The Basement Tapes','Bob Dylan and the Band','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (293,1968,'White Light/White Heat','The Velvet Underground','Rock','Avantgarde');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (294,1969,'Kick Out the Jams','MC5','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (295,1970,'Songs of Love and Hate','Leonard Cohen','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (296,1985,'Meat Is Murder','The Smiths','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (297,1968,'We''re Only in It for the Money','The Mothers of Invention','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (298,2003,'The College Dropout','Kanye West','Hip Hop','Pop Rap');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (299,1994,'Weezer (Blue name)','Weezer','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (300,1971,'Master of Reality','Black Sabbath','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (301,1971,'Coat of Many Colors','Dolly Parton','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (302,1990,'Fear of a Black Planet','Public Enemy','Hip Hop','Conscious');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (303,1967,'John Wesley Harding','Bob Dylan','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (304,1994,'Grace','Jeff Buckley','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (305,1998,'Car Wheels on a Gravel Road','Lucinda Williams','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (306,1996,'Odelay','Beck','Electronic','Hip Hop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (307,1964,'A Hard Day''s Night','The Beatles','Rock','Stage & Screen');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (308,1956,'Songs for Swingin'' Lovers!','Frank Sinatra','Jazz','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (309,1969,'Willy and the Poor Boys','Creedence Clearwater Revival','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (310,1991,'Blood Sugar Sex Magik','Red Hot Chili Peppers','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (311,1994,'The Sun Records Collection','Various','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (312,1988,'Nothing''s Shocking','Jane''s Addiction','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (313,1994,'MTV Unplugged in New York','Nirvana','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (314,1998,'The Miseducation of Lauryn Hill','Lauryn Hill','Hip Hop','RnB/Swing');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (315,1979,'Damn the Torpedoes','Tom Petty and the Heartbreakers','Rock','Soft Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (316,1969,'The Velvet Underground','The Velvet Underground','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (317,1988,'Surfer Rosa','Pixies','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (318,1972,'Back Stabbers','The O''Jays','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (319,1973,'Burnin''','The Wailers','Reggae','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (320,2001,'Amnesiac','Radiohead','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (321,1972,'Pink Moon','Nick Drake','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (322,1972,'Sail Away','Randy Newman','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (323,1981,'Ghost in the Machine','The Police','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (324,1976,'Station to Station','David Bowie','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (325,1977,'Slowhand','Eric Clapton','Rock','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (326,1989,'Disintegration','The Cure','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (327,1993,'Exile in Guyville','Liz Phair','Rock','Lo-Fi');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (328,1988,'Daydream Nation','Sonic Youth','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (329,1986,'In the Jungle Groove','James Brown','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (330,1975,'Tonight''s the Night','Neil Young','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (331,1965,'Help!','The Beatles','Rock','Stage & Screen');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (332,1982,'Shoot Out the Lights','Richard & Linda Thompson','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (333,1981,'Wild Gift','X','Rock','Rock & Roll');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (334,1979,'Squeezing Out Sparks','Graham Parker & The Rumour','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (335,1994,'Superunknown','Soundgarden','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (336,2007,'In Rainbows','Radiohead','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (337,1971,'Aqualung','Jethro Tull','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (338,1968,'Cheap Thrills','Big Brother & the Holding Company','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (339,1974,'The Heart of Saturday Night','Tom Waits','Jazz','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (340,1981,'Damaged','Black Flag','Rock','Hardcore');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (341,1999,'Play','Moby','Electronic','Breakbeat');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (342,1990,'Violator','Depeche Mode','Electronic','Synth-pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (343,1977,'Bat Out of Hell','Meat Loaf','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (344,1973,'Berlin','Lou Reed','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (345,1984,'Stop Making Sense','Talking Heads','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (346,1989,'3 Feet High and Rising','De La Soul','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (347,1967,'The Piper at the Gates of Dawn','Pink Floyd','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (348,1960,'Muddy Waters at Newport 1960','Muddy Waters','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (349,2003,'The Black name','Jay Z','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (350,1966,'Roger the Engineer','The Yardbirds','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (351,1979,'Rust Never Sleeps','Neil Young & Crazy Horse','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (352,1985,'Brothers in Arms','Dire Straits','Rock','AOR');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (353,2010,'My Beautiful Dark Twisted Fantasy','Kanye West','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (354,1978,'52nd Street','Billy Joel','Jazz','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (355,1965,'Having a Rave Up','The Yardbirds','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (356,1970,'12 Songs','Randy Newman','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (357,1967,'Between the Buttons','The Rolling Stones','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (358,1960,'Sketches of Spain','Miles Davis','Jazz','Modal');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (359,1972,'Honky Chteau','Elton John','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (360,1979,'Singles Going Steady','Buzzcocks','Rock','Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (361,2000,'Stankonia','OutKast','Hip Hop','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (362,1993,'Siamese Dream','The Smashing Pumpkins','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (363,1987,'Substance 1987','New Order','Electronic','Synth-pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (364,1971,'L.A. Woman','The Doors','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (365,1992,'Rage Against the Machine','Rage Against the Machine','Hip Hop','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (366,1994,'American Recordings','Johnny Cash','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (367,1998,'Ray of Light','Madonna','Electronic','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (368,1972,'Eagles','Eagles','Rock','Country Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (369,1987,'Louder Than Bombs','The Smiths','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (370,1973,'Mott','Mott the Hoople','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (371,2006,'Whatever People Say I Am, Thats What Im Not','Arctic Monkeys','Rock', 'Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (372,1979,'Reggatta de Blanc','The Police','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (373,1969,'Volunteers','Jefferson Airplane','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (374,1975,'Siren','Roxy Music','Rock','Art Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (375,1974,'Late for the Sky','Jackson Browne','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (376,1995,'Post','Bjork','Electronic','Breakbeat');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (377,1991,'The Ultimate Collection: 1948-1990','John Lee Hooker','Blues','Country Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (378,1995,'(What''s the Story) Morning Glory?','Oasis','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (379,0,'CrazySexyCool','XX','Electronic','XX');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (380,1973,'Funky Kingston','Toots & The Maytals','Reggae','Reggae Gospel');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (381,2011,'The Smile Sessions','The Beach Boys','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (382,1976,'The Modern Lovers','The Modern Lovers','Rock','Art Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (383,1978,'More Songs About Buildings and Food','Talking Heads','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (384,1966,'A Quick One','The Who','Rock','Mod');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (385,2001,'Love and Theft','Bob Dylan','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (386,1974,'Pretzel Logic','Steely Dan','Jazz','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (387,1993,'Enter the Wu_Tang: 36 Chambers','Wu Tang Clan','Hip Hop','Gangsta');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (388,1985,'The Indestructible Beat of Soweto','Various artists','Funk / Soul','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (389,1989,'The End of the Innocence','Don Henley','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (390,2003,'Elephant','The White Stripes','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (391,1976,'The Pretender','Jackson Browne','Rock','Soft Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (392,1970,'Let It Be','The Beatles','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (393,2007,'Kala','M.I.A.','Electronic','Hip Hop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (394,1974,'Good Old Boys','Randy Newman','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (395,2007,'Sound of Silver','LCD Soundsystem','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (396,1973,'For Your Pleasure','Roxy Music','Rock','Art Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (397,1991,'Blue Lines','Massive Attack','Electronic','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (398,1983,'Eliminator','ZZ Top','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (399,1985,'Rain Dogs','Tom Waits','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (400,1995,'Anthology: The Best of The Temptations','The Temptations','Electronic','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (401,1999,'Californication','Red Hot Chili Peppers','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (402,1994,'Illmatic','Nas','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (403,1973,'(pronounced ''leh-''nerd ''skin-''nerd)','Lynyrd Skynyrd','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (404,1972,'Dr. John''s Gumbo','Dr. John','Funk / Soul','Bayou Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (405,1974,'Radio City','Big Star','Rock','Power Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (406,1993,'Rid of Me','PJ Harvey','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (407,1980,'Sandinista!','The Clash','Rock','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (408,1989,'I Do Not Want What I Haven''t Got','Sinead O''Connor','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (409,1967,'Strange Days','The Doors','Rock','Psychedelic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (410,1997,'Time Out of Mind','Bob Dylan','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (411,1974,'461 Ocean Boulevard','Eric Clapton','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (412,1977,'Pink Flag','Wire','Rock','Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (413,1984,'Double Nickels on the Dime','Minutemen','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (414,1981,'Beauty and the Beat','The Go Go''s','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (415,1978,'Van Halen','Van Halen','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (416,1999,'Mule Variations','Tom Waits','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (417,1980,'Boy','U2','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (418,1973,'Band on the Run','Paul McCartney & Wings','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (419,1994,'Dummy','Portishead','Electronic','Trip Hop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (420,1957,'The Chirping Crickets','The Crickets','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (421,1990,'The Best of the Girl Groups, Volume 1','Various artists','Rock', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (422,1963,'Presenting the Fabulous Ronettes Featuring Veronica','The Ronettes','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (423,2001,'Anthology','Diana Ross & The Supremes','Electronic','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (424,2002,'The Rising','Bruce Springsteen','Rock','Folk Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (425,1974,'Grievous Angel','Gram Parsons','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (426,1978,'Cheap Trick at Budokan','Cheap Trick','Rock','Power Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (427,2002,'Sleepless','Peter Wolf','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (428,1978,'Outlandos d''Amour','The Police','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (429,1975,'Another Green World','Brian Eno','Electronic','Experimental');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (430,2007,'Vampire Weekend','Vampire Weekend','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (431,2000,'Stories From the City,Stories From the Sea','PJ Harvey','Rock', 'Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (432,1973,'Here Come the Warm Jets','Brian Eno','Rock','Art Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (433,1970,'All Things Must Pass','George Harrison','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (434,1972,'#1 Record','Big Star','Rock','Power Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (435,1993,'In Utero','Nirvana','Rock','Grunge');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (436,2002,'Sea Change','Beck','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (437,2008,'Tha Carter III','Lil Wayne','Hip Hop','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (438,1979,'Boys Don''t Cry','The Cure','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (439,1985,'Live at the Harlem Square Club 1963','Sam Cooke','Funk / Soul','Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (440,1985,'Rum Sodomy & the Lash','The Pogues','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (441,1977,'Suicide','Suicide','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (442,1978,'Q: Are We Not Men? A: We Are Devo!','DEVO','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (443,1977,'In Color','Cheap Trick','Rock','Power Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (444,1972,'The World Is a Ghetto','War','Funk / Soul','Funk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (445,1976,'Fly Like an Eagle','Steve Miller Band','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (446,1970,'Back in the USA','MC5','Rock','Garage Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (447,1964,'Getz / Gilberto','Stan Getz/Joao GilbertofeaturingAntonio Carlos Jobim','Jazz','Bossa Nova');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (448,1983,'Synchronicity','The Police','Rock','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (449,1978,'Third/Sister Lovers','Big Star','Rock','Lo-Fi');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (450,1973,'For Everyman','Jackson Browne','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (451,2006,'Back to Black','Amy Winehouse','Funk / Soul','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (452,1971,'John Prine','John Prine','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (453,1987,'Strictly Business','EPMD','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (454,1971,'Love It to Death','Alice Cooper','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (455,1984,'How Will the Wolf Survive?','Los Lobos','Rock','Latin');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (456,1978,'Here, My Dear','Marvin Gaye','Funk / Soul', 'Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (457,2005,'Z','My Morning Jacket','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (458,1970,'Tumbleweed Connection','Elton John','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (459,1968,'The Drifters'' Golden Hits','The Drifters','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (460,1994,'Live Through This','Hole','Rock','Grunge');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (461,1979,'Metal Box','Public Image Ltd.','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (462,1987,'Document','R.E.M.','Rock','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (463,1981,'Heaven Up Here','Echo and The Bunnymen','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (464,1987,'Hysteria','Def Leppard','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (465,1999,'69 Love Songs','The Magnetic Fields','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (466,2002,'A Rush of Blood to the Head','Coldplay','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (467,1987,'Tunnel of Love','Bruce Springsteen','Rock','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (468,1965,'The Paul Butterfield Blues Band','The Paul Butterfield Blues Band','Rock','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (469,1996,'The Score','Fugees','Hip Hop','Pop Rap');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (470,1985,'Radio','L.L. Cool J','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (471,1974,'I Want to See the Bright Lights Tonight','Richard & Linda Thompson','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (472,1987,'Faith','George Michael','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (473,1984,'The Smiths','The Smiths','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (474,2001,'Proxima estacion: Esperanza','Manu Chao','Rock','Reggae');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (475,1979,'Armed Forces','Elvis Costello & The Attractions','Rock','New Wave');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (476,1997,'Life After Death','The Notorious B.I.G.','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (477,1996,'Down Every Road','Merle Haggard','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (478,2002,'All Time Greatest Hits','Loretta Lynn','Folk','World');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (479,1971,'Maggot Brain','Funkadelic','Rock','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (480,1995,'Only Built 4 Cuban Linx','Raekwon','Hip Hop','None');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (481,2000,'Voodoo','D''Angelo','Hip Hop','Funk / Soul');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (482,1986,'Guitar Town','Steve Earle','Rock','Folk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (483,1979,'Entertainment!','Gang of Four','Rock','Post-Punk');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (484,1972,'All the Young Dudes','Mott the Hoople','Rock','Classic Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (485,1994,'Vitalogy','Pearl Jam','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (486,1975,'That''s the Way of the World','Earth, Wind & Fire','Funk / Soul', NULL);
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (487,1983,'She''s So Unusual','Cyndi Lauper','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (488,1985,'New Day Rising','Husker Du','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (489,1976,'Destroyer','KISS','Rock','Hard Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (490,1973,'Tres hombres','ZZ Top','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (491,1967,'Born Under a Bad Sign','Albert King','Funk / Soul','Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (492,1983,'Touch','Eurythmics','Electronic','Pop');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (493,2002,'Yankee Hotel Foxtrot','Wilco','Rock','Alternative Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (494,2007,'Oracular Spectacular','MGMT','Electronic','Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (495,1972,'Give It Up','Bonnie Raitt','Rock','Blues Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (496,1969,'Boz Scaggs','Boz Scaggs','Rock','Pop Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (497,2001,'White Blood Cells','The White Stripes','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (498,1989,'The Stone Roses','The Stone Roses','Rock','Indie Rock');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (499,1971,'Live in Cook County Jail','B.B. King','Blues','Electric Blues');
INSERT INTO album(position,year,name,artist,genre,subgenre) VALUES (500,1998,'Aquemini','OutKast','Hip Hop','Reggae');